name: Close Milestone

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed

jobs:
  close:
    name: Close completed milestone
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Close a milestone if completed
        run: |
          milestones=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/milestones \
            | jq -r '. | map(select(.open_issues == 0 and .closed_issues > 0 and .state == "open"))')
          if [ "$milestones" != "[]" ]
          then
            milestone_number=$(echo "$milestones" | jq -r '.[0].number')
            curl --request PATCH \
              --url https://api.github.com/repos/${{ github.repository }}/milestones/${milestone_number} \
              --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              --header 'Content-Type: application/json' \
              --data '{"state":"closed"}'
          fi

